### ISSUE TITLE
Using stale in combination with struct breaks Bootstrap3 template

### ISSUE THREAD

**Issue by jgod** [ComboStrap/stale#6]
[Struct](https://github.com/cosmocode/dokuwiki-plugin-struct)

* breaks Bootstrap3 navbar (unable to access Admin config menu)
* icons don't load

**Comment by gerardnico** [comment]
See the pinned issue number #1 or search the history for the other.

This problem is the only one that has opened issues and this is not the fault of stale but bootstrap3.
